/*
	USE MASTER
	GO
	DROP DATABASE JAVA_LAB6
	GO
*/
CREATE DATABASE JAVA_LAB6
GO

USE JAVA_LAB6
GO

CREATE TABLE Books (
	ID INT IDENTITY PRIMARY KEY,
	title NVARCHAR(50),
	price FLOAT
)
GO
INSERT INTO Books (title, price) VALUES (N'Lập trình C',100)
INSERT INTO Books (title, price) VALUES (N'Lập trình Java',200)
INSERT INTO Books (title, price) VALUES (N'Lập trình C#',150)
GO

CREATE TABLE STANDARS
(
	MATIEUCHUAN VARCHAR(10) PRIMARY KEY,
	PHI INT
)
GO


CREATE TABLE STUDENTS
(
	MAHOCSINH VARCHAR(10) PRIMARY KEY,
	TENHOCSINH NVARCHAR(50),
	DIACHI NVARCHAR(50),
	TENCHAME NVARCHAR(50),
	DIENTHOAI VARCHAR(10),
	MATIEUCHUAN VARCHAR(10) REFERENCES STANDARS (MATIEUCHUAN)
)
GO

INSERT INTO STANDARS VALUES('TC01', 100)
INSERT INTO STANDARS VALUES('TC02', 150)
INSERT INTO STANDARS VALUES('TC03', 200)
GO

INSERT INTO STUDENTS VALUES('HS01', N'Đỗ Văn Hào', N'116 Nguyễn Phúc Chu', N'Đỗ Văn Phong', '0385654546', 'TC01')
INSERT INTO STUDENTS VALUES('HS02', N'Nguyễn Minh Châu', N'Q11 TPHCM', N'Nguyễn Minh Chiến', '0965875421', 'TC02')
INSERT INTO STUDENTS VALUES('HS03', N'Lê Thị Bóng', N'11 Lý Chiến Thắng Q3 TPHCM', N'Lê Văn Luyện', '0985474512', 'TC03')
GO

SELECT * FROM STUDENTS
SELECT * FROM STANDARS

SELECT * FROM STUDENTS WHERE MATIEUCHUAN = 'TC03'